### ISSUE TITLE
Explain the use of the configuration file

### ISSUE THREAD

**Issue by cschwan** [cschwan/managed-lhapdf#2]
See <https://github.com/NNPDF/pineappl/issues/303>.

**Comment by cschwan** [comment]
@felixhekhorn, please have a look at the updated `README.md` and give me some feedback.

**Comment by felixhekhorn** [comment]
```
# can be given as # strings seperated by commas.
```
Remove the second `#` which seems to be a remanent 

---

by putting a default with `nnpdf.science` you're tying it to NNPDF - not sure you want that ...

---

I'd still mention it prominently directly in pineappl somewhere

**Comment by cschwan** [comment]
> ```
> # can be given as # strings seperated by commas.
> ```
> 
> Remove the second `#` which seems to be a remanent
> 
> by putting a default with `nnpdf.science` you're tying it to NNPDF - not sure you want that ...
> 
> I'd still mention it prominently directly in pineappl somewhere

In af19ae6cc61283b2499ebdeed2ae24f1b14e4fbe I now mention that this is a customized configuration. The default only includes the first URL. In PineAPPL we should mention this configuration file also, agreed.

**Comment by felixhekhorn** [comment]
Readme seems good now. Good for the URL.
